// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSopGxIpUN5ndCLKb1gHwTg8HVgaf61L4',
    appId: '1:222824754064:web:5d8a52c1a98c3dc3982115',
    messagingSenderId: '222824754064',
    projectId: 'extra-classes-2b1d8',
    authDomain: 'extra-classes-2b1d8.firebaseapp.com',
    databaseURL: 'https://extra-classes-2b1d8-default-rtdb.firebaseio.com',
    storageBucket: 'extra-classes-2b1d8.appspot.com',
    measurementId: 'G-79ZF3TD57T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxmJ-9qiP2Eh3tSFLSPJUAfRkHi1O0wKc',
    appId: '1:222824754064:android:56280772ed78ccf9982115',
    messagingSenderId: '222824754064',
    projectId: 'extra-classes-2b1d8',
    databaseURL: 'https://extra-classes-2b1d8-default-rtdb.firebaseio.com',
    storageBucket: 'extra-classes-2b1d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLi5LPlj9IUocANqOOADl_qxWh9VkYBY',
    appId: '1:222824754064:ios:af2e781ced6f469b982115',
    messagingSenderId: '222824754064',
    projectId: 'extra-classes-2b1d8',
    databaseURL: 'https://extra-classes-2b1d8-default-rtdb.firebaseio.com',
    storageBucket: 'extra-classes-2b1d8.appspot.com',
    androidClientId: '222824754064-nadu9tk5j5h8vei1mv01cohh36tnqvun.apps.googleusercontent.com',
    iosClientId: '222824754064-qavodqfle94sonognhen1gid4ehu4r5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.extraClasses',
  );
}
